-- Find Employees whose Last Name starts with 'S'  
-- Find Employees whose First Name ends with 'a'  
-- Find Employees whose Department contains 'Eng'  
-- Find Employees whose Last Name is exactly 5 characters long  
-- Find Employees whose First Name starts with 'C' or 'D'  
-- Find Employees whose Last Name contains 'son'  
-- Find Employees whose First Name contains the letter 'i' as the second character  
-- Find Employees whose Last Name starts with any letter between 'A' and 'L'  
-- Find Employees whose First Name does not contain 'o'  
-- Find Employees whose Last Name ends with 'a' and is exactly 5 characters long  
-- Find Employees whose Department starts with 'Mar' and ends with 'ing'  
-- Find Employees whose First Name has an 'a' in the third position  
-- Find Employees whose Last Name starts with 'Br' or 'Bl'  